# Generated by Django 4.2.1 on 2023-05-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooterrentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('permanent_address', models.TextField()),
                ('id_proof_type', models.CharField(choices=[('driving_license', 'Driving License'), ('aadhar', 'Aadhar')], max_length=50)),
                ('id_proof_image', models.ImageField(upload_to='id_proof_images')),
                ('id_proof_number', models.CharField(max_length=50)),
                ('rider_image', models.ImageField(upload_to='rider_images')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooterrentapp.scooter')),
            ],
        ),
    ]
